2018-01-31 17:47:39 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Unknown data type: "VARHCAR"; SQL statement:
CREATE TABLE IF NOT EXISTS utilisateurs (id INT AUTO_INCREMENT (0, 1) PRIMARY KEY,nom VARCHAR(35) NOT NULL,prenom VARCHAR(35) NOT NULL,pseudo VARHCAR(35) NOT NULL UNIQUE,email VARCHAR(35) NOT NULL UNIQUE,films_loue VARCHAR(1000),solde DECIMAL NOT NULL,role VARCHAR(6) NOT NULL); [50004-196]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.command.Parser.parseColumnWithType(Parser.java:4169)
	at org.h2.command.Parser.parseColumnForTable(Parser.java:4012)
	at org.h2.command.Parser.parseCreateTable(Parser.java:6155)
	at org.h2.command.Parser.parseCreate(Parser.java:4351)
	at org.h2.command.Parser.parsePrepared(Parser.java:366)
	at org.h2.command.Parser.parse(Parser.java:321)
	at org.h2.command.Parser.parse(Parser.java:293)
	at org.h2.command.Parser.prepareCommand(Parser.java:258)
	at org.h2.engine.Session.prepareLocal(Session.java:578)
	at org.h2.engine.Session.prepareCommand(Session.java:519)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1204)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:73)
	at org.h2.jdbc.JdbcCallableStatement.<init>(JdbcCallableStatement.java:51)
	at org.h2.jdbc.JdbcConnection.prepareCall(JdbcConnection.java:912)
	at bdd.BaseDeDonnee.createTables(BaseDeDonnee.java:49)
	at bdd.BaseDeDonnee.<init>(BaseDeDonnee.java:22)
	at bdd.BaseDeDonnee.main(BaseDeDonnee.java:102)
